owner: connecthear  # Your GitHub username
repo: v1-app-uptime # The name of this repository

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Trigger the `main.yml` workflow
    - name: Trigger main.yml Workflow
      id: trigger_main
      run: |
        curl -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches \
        -d '{"ref":"main"}'
    
    # Step 2: Wait for the completion of `main.yml` (Polling)
    - name: Wait for main.yml completion
      id: wait_for_main
      run: |
        workflow_id=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/repos/${{ github.repository }}/actions/runs \
        | jq -r '.workflow_runs[] | select(.name == "Custom Uptime Workflow" and .status == "in_progress") | .id')

        echo "Waiting for workflow $workflow_id to complete..."

        while [[ $(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/actions/runs/$workflow_id | jq -r '.status') == "in_progress" ]]; do
          echo "Workflow is still in progress... waiting 30 seconds"
          sleep 30
        done
        
        status=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/actions/runs/$workflow_id | jq -r '.conclusion')

        if [[ "$status" != "success" ]]; then
          echo "Custom Uptime Workflow Workflow failed"
          exit 1
        fi
        echo "Custom Uptime Workflow completed successfully"

sites:
  - name: Customer Sign-Up API
    url: https://app.connecthear.org/api/v1/customer/sign-up
    method: POST
    body: '{"name": "Test User", "email": "uptime@connecthear.org", "password": "connecthearapplicationdevelopment","date_of_birth": "1990-01-01","mobile_number": "1234567890","gender": "Male","latitude": "25.276987","longitude": "55.296249","code": ""}'
    expectedStatusCodes:
      - 200
      - 201
      - 422
    check: "http"
    headers:
      - "Content-Type: application/json"
  - name: Customer Login API # Monitoring the login API
    url: https://app.connecthear.org/api/v1/customer/login
    method: POST
    body: '{"email": "uptime@connecthear.org", "password": "connecthearapplicationdevelopment"}'
    expectedStatusCodes:
      - 200
      - 401
      - 422
    check: "http"
    headers:
      - "Content-Type: application/json"
      
  - name: Customer Google Login API # Monitoring the Google Login API
    url: https://app.connecthear.org/api/v1/customer/google-login
    method: POST
    body: '{"name": "Upptime", "email": "uptime@connecthear.org", "google_id": "{{TOKEN}}"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "http"
    headers:
      - "Content-Type: application/json"
  - name: Customer Forgot Password API # Monitoring the Forgot Password API
    url: https://app.connecthear.org/api/v1/customer/forgot-password
    method: POST
    body: '{"email": "uptime@connecthear.org"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "http"
    headers:
      - "Content-Type: application/json"
  - name: Customer Code Verification API # Monitoring the Verify Code API
    url: https://app.connecthear.org/api/v1/customer/verify-code
    method: POST
    body: '{"email": "uptime@connecthear.org", "verification_code": "1234", "password": "connecthearapplicationdevelopment", "password_confirmation": "connecthearapplicationdevelopment1"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "http"
    headers:
      - "Content-Type: application/json"
  - name: Customer SMS Code Verification API # Monitoring the Verify SMS Code API
    url: https://app.connecthear.org/api/v1/customer/verify-sms-code
    method: POST
    body: '{"email": "uptime@connecthear.org", "password": "connecthearapplicationdevelopment", "mobile_number": "1234567890", "verification_code": "1234"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "http"
    headers:
      - "Content-Type: application/json"
  - name: Customer Password Reset API # Monitoring the Reset Password API
    url: https://app.connecthear.org/api/v1/customer/reset-password
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{"email": "uptime@connecthear.org", "password": "connecthearapplicationdevelopment", "password_confirmation": "connecthearapplicationdevelopment"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "http"
  - name: Customer Resend OTP API # Monitoring the Resend OTP API
    url: https://app.connecthear.org/api/v1/customer/resend-otp
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{"email": "uptime@connecthear.org"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "http"
  - name: Customer Get Profile API # Monitoring the Get Profile API
    url: https://app.connecthear.org/api/v1/customer/get-profile
    method: GET
    headers:
      - "Content-Type: application/json;charset=UTF-8"
      - "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImY2NmVjZTA0MTNlNTQ5M2E4Nzk3ZmViZGEyMWU0MjdlY2NlODA3Zjg4NTQ5MDYwNDk3MmE0YTA1MjNlYzQ0ZjA2MmFlZmY3YzQxNDk2OTUyIn0.eyJhdWQiOiIxIiwianRpIjoiZjY2ZWNlMDQxM2U1NDkzYTg3OTdmZWJkYTIxZTQyN2VjY2U4MDdmODg1NDkwNjA0OTcyYTRhMDUyM2VjNDRmMDYyYWVmZjdjNDE0OTY5NTIiLCJpYXQiOjE3MjkwMDI3MTksIm5iZiI6MTcyOTAwMjcxOSwiZXhwIjoxNzYwNTM4NzE5LCJzdWIiOiIxNTY4NCIsInNjb3BlcyI6W119.BZogqb8ZH2mAr49Q-Zc3bKObMx4QOVP7xx7CBldv9kyTKvpQw8MnhoAHBsMfkHKbdpy6d5rF3BYYEiU5_pz3jjwtGiGPH_msVKZxnuMF8gpCzOGzvGix44G3tGwXrd2pv8JoP1KfkaNDnsMd4qF5UF_rdbyVZF0M-WDrWDEpz3f5A2v5E8CVHpxjkTdoXcwTBXBC9KX0b9TSQEHr2uR0LUfznCaTRCvwvu3iuQtwdkOYuMp1Qsx2ncXXhlwWAe5et3XdxHoWQeNBstcGUt2vS7RtWom3pYaUNBgdtTErhJcZ5Ao4tNyq6Nimrkn_UY6KsBoyIL82SS8NBykn8cdT93quz6gzcaKu_OG8JVmZvNrAE6D2p_pwH2PTDcVTuHbsQOeQXQNreIcY_aX4IAS345FMC2ZH37hJh4Qvb8CuWHm4s-AeWFcNlSRjZYr0FJG8m1hR6nxXr639o_WFu2uU05kSAHii_GGkIxZxcQ7MOzIckyPhtRz6O9BssOXU3qp55RxBNCwDzaF1r4v79QIyz2vxHeAE5NnDBYiNBvM_mnSRYKDGP6eMf14nLRKpJCWVMKWfJPm3noCquIaXK-Jv0wKRKq1PRwFYP_wuG2cRjDHgYV2gfllZK-0TL96eHHFm6USaIXXntDBRsYKZp_3D5KsPqdut2jgFzSU6iLRyyW4"  # Token will be dynamically replaced
    expectedStatusCodes:
      - 200
      - 403  # Account disabled by user or company
    check: "http"
  - name: Customer Change Password API # Monitoring the Change Password API
    url: https://app.connecthear.org/api/v1/customer/change-password
    method: POST
    headers:
      - "Content-Type: application/json"
      - "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImY2NmVjZTA0MTNlNTQ5M2E4Nzk3ZmViZGEyMWU0MjdlY2NlODA3Zjg4NTQ5MDYwNDk3MmE0YTA1MjNlYzQ0ZjA2MmFlZmY3YzQxNDk2OTUyIn0.eyJhdWQiOiIxIiwianRpIjoiZjY2ZWNlMDQxM2U1NDkzYTg3OTdmZWJkYTIxZTQyN2VjY2U4MDdmODg1NDkwNjA0OTcyYTRhMDUyM2VjNDRmMDYyYWVmZjdjNDE0OTY5NTIiLCJpYXQiOjE3MjkwMDI3MTksIm5iZiI6MTcyOTAwMjcxOSwiZXhwIjoxNzYwNTM4NzE5LCJzdWIiOiIxNTY4NCIsInNjb3BlcyI6W119.BZogqb8ZH2mAr49Q-Zc3bKObMx4QOVP7xx7CBldv9kyTKvpQw8MnhoAHBsMfkHKbdpy6d5rF3BYYEiU5_pz3jjwtGiGPH_msVKZxnuMF8gpCzOGzvGix44G3tGwXrd2pv8JoP1KfkaNDnsMd4qF5UF_rdbyVZF0M-WDrWDEpz3f5A2v5E8CVHpxjkTdoXcwTBXBC9KX0b9TSQEHr2uR0LUfznCaTRCvwvu3iuQtwdkOYuMp1Qsx2ncXXhlwWAe5et3XdxHoWQeNBstcGUt2vS7RtWom3pYaUNBgdtTErhJcZ5Ao4tNyq6Nimrkn_UY6KsBoyIL82SS8NBykn8cdT93quz6gzcaKu_OG8JVmZvNrAE6D2p_pwH2PTDcVTuHbsQOeQXQNreIcY_aX4IAS345FMC2ZH37hJh4Qvb8CuWHm4s-AeWFcNlSRjZYr0FJG8m1hR6nxXr639o_WFu2uU05kSAHii_GGkIxZxcQ7MOzIckyPhtRz6O9BssOXU3qp55RxBNCwDzaF1r4v79QIyz2vxHeAE5NnDBYiNBvM_mnSRYKDGP6eMf14nLRKpJCWVMKWfJPm3noCquIaXK-Jv0wKRKq1PRwFYP_wuG2cRjDHgYV2gfllZK-0TL96eHHFm6USaIXXntDBRsYKZp_3D5KsPqdut2jgFzSU6iLRyyW4"  # Token will be dynamically replaced
    body: '{"current_password": "your_current_password_here", "password": "your_new_password_here", "password_confirmation": "your_new_password_here"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "http"
  - name: Customer Update Device Token API # Monitoring the Update Device Token API
    url: https://app.connecthear.org/api/v1/customer/update-device-token
    method: POST
    headers:
      - "Content-Type: application/json"
      - "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImY2NmVjZTA0MTNlNTQ5M2E4Nzk3ZmViZGEyMWU0MjdlY2NlODA3Zjg4NTQ5MDYwNDk3MmE0YTA1MjNlYzQ0ZjA2MmFlZmY3YzQxNDk2OTUyIn0.eyJhdWQiOiIxIiwianRpIjoiZjY2ZWNlMDQxM2U1NDkzYTg3OTdmZWJkYTIxZTQyN2VjY2U4MDdmODg1NDkwNjA0OTcyYTRhMDUyM2VjNDRmMDYyYWVmZjdjNDE0OTY5NTIiLCJpYXQiOjE3MjkwMDI3MTksIm5iZiI6MTcyOTAwMjcxOSwiZXhwIjoxNzYwNTM4NzE5LCJzdWIiOiIxNTY4NCIsInNjb3BlcyI6W119.BZogqb8ZH2mAr49Q-Zc3bKObMx4QOVP7xx7CBldv9kyTKvpQw8MnhoAHBsMfkHKbdpy6d5rF3BYYEiU5_pz3jjwtGiGPH_msVKZxnuMF8gpCzOGzvGix44G3tGwXrd2pv8JoP1KfkaNDnsMd4qF5UF_rdbyVZF0M-WDrWDEpz3f5A2v5E8CVHpxjkTdoXcwTBXBC9KX0b9TSQEHr2uR0LUfznCaTRCvwvu3iuQtwdkOYuMp1Qsx2ncXXhlwWAe5et3XdxHoWQeNBstcGUt2vS7RtWom3pYaUNBgdtTErhJcZ5Ao4tNyq6Nimrkn_UY6KsBoyIL82SS8NBykn8cdT93quz6gzcaKu_OG8JVmZvNrAE6D2p_pwH2PTDcVTuHbsQOeQXQNreIcY_aX4IAS345FMC2ZH37hJh4Qvb8CuWHm4s-AeWFcNlSRjZYr0FJG8m1hR6nxXr639o_WFu2uU05kSAHii_GGkIxZxcQ7MOzIckyPhtRz6O9BssOXU3qp55RxBNCwDzaF1r4v79QIyz2vxHeAE5NnDBYiNBvM_mnSRYKDGP6eMf14nLRKpJCWVMKWfJPm3noCquIaXK-Jv0wKRKq1PRwFYP_wuG2cRjDHgYV2gfllZK-0TL96eHHFm6USaIXXntDBRsYKZp_3D5KsPqdut2jgFzSU6iLRyyW4"  # Token will be dynamically replaced
    body: '{"device_token": "your_device_token_here", "device_type": "your_device_type_here"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "http"

# Additional APIs can be added following the same structure

status-website:
  baseUrl: /v1-app-uptime
  logoUrl: https://avatars.githubusercontent.com/u/94858144?s=400&u=21671f502bedc2181ba2a90086fcf842d6231d1c&v=4
  name: ConnectHear v1 App Uptime
  introTitle: "This is ConnectHear's uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/ConnectHear/v1-app-uptime). No server required — just GitHub Actions, Issues, and Pages. 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/connecthear/v1-app-uptime
