owner: connecthear # Your GitHub username
repo: v1-app-uptime # The name of this repository

sites:
  - name: Customer Sign-Up API
    url: https://app.connecthear.org/api/v1/customer/sign-up
    method: POST
    body: '{"name": "Test User", "email": "uptime@connecthear.org", "password": "connecthearapplicationdevelopment","date_of_birth": "1990-01-01","mobile_number": "1234567890","gender": "Male","latitude": "25.276987","longitude": "55.296249","code": ""}'
    expectedStatusCodes:
      - 200
      - 201
      - 422
    check: "http"
    headers:
      - "Content-Type: application/json"

  - name: Customer Login API
    url: https://app.connecthear.org/api/v1/customer/login
    method: POST
    body: '{"email": "uptime@connecthear.org", "password": "connecthearapplicationdevelopment"}'
    expectedStatusCodes:
      - 200
      - 401
      - 422
    check: "http"
    headers:
      - "Content-Type: application/json"

  - name: Customer Google Login API
    url: https://app.connecthear.org/api/v1/customer/google-login
    method: POST
    body: '{"name": "Upptime", "email": "uptime@connecthear.org", "google_id": "your_google_id"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "http"
    headers:
      - "Content-Type: application/json"

  - name: Customer Forgot Password API
    url: https://app.connecthear.org/api/v1/customer/forgot-password
    method: POST
    body: '{"email": "uptime@connecthear.org"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "http"
    headers:
      - "Content-Type: application/json"

  - name: Customer Code Verification API
    url: https://app.connecthear.org/api/v1/customer/verify-code
    method: POST
    body: '{"email": "uptime@connecthear.org", "verification_code": "1234", "password": "connecthearapplicationdevelopment", "password_confirmation": "connecthearapplicationdevelopment1"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "http"
    headers:
      - "Content-Type: application/json"

  - name: Customer Get Profile API
    url: https://app.connecthear.org/api/v1/customer/get-profile
    method: GET
    headers:
      - "Content-Type: application/json"
      - "Authorization: Bearer {{ACCESS_TOKEN}}"
    expectedStatusCodes:
      - 200
      - 403
    check: "http"

  - name: Customer Update Device Token API
    url: https://app.connecthear.org/api/v1/customer/update-device-token
    method: POST
    body: '{"device_token": "your_device_token_here", "device_type": "your_device_type_here"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "http"
    headers:
      - "Content-Type: application/json"
      - "Authorization: Bearer {{ACCESS_TOKEN}}"

  - name: Interpreter Sign-Up API
    url: https://app.connecthear.org/api/v1/interpreter/sign-up
    method: POST
    body: '{"name": "Upptime", "email": "uptime@connecthear.org", "password": "connecthearapplicationdevelopment", "mobile_number": "1234567890", "gender": "male", "date_of_birth": "1990-01-01", "occupation": "Interpreter", "address": "123 Main St", "latitude": "34.0522", "longitude": "-118.2437", "avatar": "base64_encoded_image", "cnic": "base64_encoded_cnic"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "http"
    headers:
      - "Content-Type: application/json"

  - name: Interpreter Google Login API
    url: https://app.connecthear.org/api/v1/interpreter/google-login
    method: POST
    body: '{"name": "Upptime", "email": "uptime@connecthear.org", "google_id": "your_google_id"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "http"
    headers:
      - "Content-Type: application/json"

status-website:
  baseUrl: /v1-app-uptime
  logoUrl: https://avatars.githubusercontent.com/u/94858144?s=400&u=21671f502bedc2181ba2a90086fcf842d6231d1c&v=4
  name: ConnectHear v1 App Uptime
  introTitle: "This is ConnectHear's uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/ConnectHear/v1-app-uptime). No server required — just GitHub Actions, Issues, and Pages. 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/connecthear/v1-app-uptime
