owner: connecthear # Your GitHub username
repo: v1-app-uptime # The name of this repository

sites:
  - name: Customer Sign-Up API
    url: https://app.connecthear.org/api/v1/customer/sign-up
    method: POST
    body: '{"name": "Test User", "email": "testuser@example.com", "password": "password1234","date_of_birth": "1990-01-01","mobile_number": "1234567890","gender": "Male","latitude": "25.276987","longitude": "55.296249","code": ""}'
    expectedStatusCodes:
      - 200
      - 201
      - 422
    check: "https"
    headers:
      - "Content-Type: application/json"
  - name: Customer Login API # Monitoring the login API
    url: https://app.connecthear.org/api/v1/customer/login
    method: POST
    body: '{"email": "testuser@example.com", "password": "password1234"}'
    expectedStatusCodes:
      - 200
      - 401
      - 422
    check: "http"
    headers:
      - "Content-Type: application/json"
  - name: Customer Google Login API # Monitoring the Google Login API
    url: https://app.connecthear.org/api/v1/customer/google-login
    method: POST
    body: '{"name": "Test User", "email": "testuser@example.com", "google_id": "google-test-id-123"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "http"
    headers:
      - "Content-Type: application/json"
  - name: Customer Forgot Password API # Monitoring the Forgot Password API
    url: https://app.connecthear.org/api/v1/customer/forgot-password
    method: POST
    body: '{"email": "testuser@example.com"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "http"
    headers:
      - "Content-Type: application/json"
  - name: Customer Code Verfication API # Monitoring the Verify Code API
    url: https://app.connecthear.org/api/v1/customer/verify-code
    method: POST
    body: '{"email": "testuser@example.com", "verification_code": "1234", "password": "newpassword", "password_confirmation": "newpassword"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "http"
    headers:
      - "Content-Type: application/json"
  - name: Customer sms Code Verification API # Monitoring the Verify SMS Code API
    url: https://app.connecthear.org/api/v1/customer/verify-sms-code
    method: POST
    body: '{"email": "testuser@example.com", "password": "strongpassword", "mobile_number": "1234567890", "verification_code": "1234"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "http"
    headers:
      - "Content-Type: application/json"
  - name: Customer Password Reset API # Monitoring the Reset Password API
    url: https://app.connecthear.org/api/v1/customer/reset-password
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{"email": "user@example.com", "password": "newpassword123", "password_confirmation": "newpassword123"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "http"
  - name: Customer Resend OTP API # Monitoring the Resend OTP API
    url: https://app.connecthear.org/api/v1/customer/resend-otp
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{"email": "user@example.com"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "http"
  - name: Customer Get Profile API # Monitoring the Get Profile API
    url: https://app.connecthear.org/api/v1/customer/get-profile
    method: GET
    headers:
      - "Content-Type: application/json;charset=UTF-8n"
      - "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImYzOTU2NzQxMmRmNDc5NTEyZjg1MDVlNTg5NWE4NjFjM2VlYjM2YTNhNzk1NzFhNWMzMTk2YTBlODE4ZjRmYjc1NzU0NTc5NWE0NTRlNjg3In0.eyJhdWQiOiIxIiwianRpIjoiZjM5NTY3NDEyZGY0Nzk1MTJmODUwNWU1ODk1YTg2MWMzZWViMzZhM2E3OTU3MWE1YzMxOTZhMGU4MThmNGZiNzU3NTQ1Nzk1YTQ1NGU2ODciLCJpYXQiOjE3MjYxMjE2ODAsIm5iZiI6MTcyNjEyMTY4MCwiZXhwIjoxNzU3NjU3NjgwLCJzdWIiOiIxNDY2MyIsInNjb3BlcyI6W119.lP6RbNpKDPofX6BAINK-wK2mSNLmSwchibHHXqnlWqIV0uOaGqkUKMu84rc1bwsjFHb-ePZKlncab6qeLUwNCMMzqGcUNouSPvlrxZq16dLXQdAVLTUKZpFpKZoJl-rjCzNvJ8sU-uzYjARCftQcmLocoUloQ4fubMAPQ4RH8bSpC2lsAr7CwX2WRIS_0us67N_xNV6tHCjW7akoxviba6kmHU98oIoAU5ZI6SOvphhT4WI6RExcYymgEPWdkzxOLYCdpFOv69CGVS3sfo2ipTlirRSlmD6ek6BKATmbJfs1FtKSXACG8JwQ930hPV2lf51OlPaaPAyLtUhGEp4BmNB_6t8fdkFS0Pc422dzfP8G3l1tpnHHjCRPZ3C5pyB-vZa-Tz92L_wEAlCFvlLQy8fKEjq4ROyph0PB5EY8xBZ57PuusCOxjJqtBfoVMxFL0iz_O546pb4ufAV-qRxElehQFUztzW54pGQFBdNWW9oDmXg6DFI3OjViTwkS_PAPgQzeOwLoF09IZxZ4I8clfZ6fdk-jSrZsztkuVUm5g0vrlGfYCxsnsW44cJP4lwqWxUq9F5TFK6MAdY6oMA-YolvAjnXKqWwViPJvdAckeBpiilKGAqqLq58pta0yVQAOVb-dgMyTeCTxnhF_hhczsk9iiSSpMoiPzBVwxooHDVM"  # Replace YOUR_ACCESS_TOKEN with a valid token or use a secret
    expectedStatusCodes:
      - 200
      - 403  # Account disabled by user or company
    check: "http"

  # - name: Customer Logout API # Monitoring the Logout API
  #   url: https://app.connecthear.org/api/v1/customer/logout
  #   method: POST
  #   headers:
  #     - "Content-Type: application/json"
  #     - "Authorization: Bearer YOUR_ACCESS_TOKEN"  # Replace YOUR_ACCESS_TOKEN with a valid token or use a secret
  #   expectedStatusCodes:
  #     - 200
  #   check: "http"

  # - name: Customer Update Device Token API # Monitoring the Update Device Token API
  #   url: https://app.connecthear.org/api/v1/customer/update-device-token
  #   method: POST
  #   headers:
  #     Content-Type: application/json
  #     Authorization: "Bearer YOUR_ACCESS_TOKEN" # Replace with a valid token
  #   expectedStatusCodes: [200, 422] # 200 for success, 422 for validation errors
  #   check: "http"
  # - name: Customer Change Password API # Monitoring the Change Password API
  #   url: https://app.connecthear.org/api/v1/customer/change-password
  #   method: POST
  #   headers:
  #     Content-Type: application/json
  #     Authorization: "Bearer YOUR_ACCESS_TOKEN" # Replace with a valid token
  #   expectedStatusCodes: [200, 422] # 200 for success, 422 for validation errors
  #   check: "http"
  # - name: Customer Update Device Token API # Monitoring the Update Device Token API
  #   url: https://app.connecthear.org/api/v1/customer/update-device-token
  #   method: POST
  #   headers:
  #     - "Content-Type: application/json"
  #     - "Authorization: Bearer YOUR_ACCESS_TOKEN"  # Replace YOUR_ACCESS_TOKEN with a valid token or use a secret
  #   body: '{"device_token": "your_device_token_here", "device_type": "your_device_type_here"}'
  #   expectedStatusCodes:
  #     - 200
  #     - 422
  #   check: "http"
  # - name: Customer Change Password API # Monitoring the Change Password API
  #   url: https://app.connecthear.org/api/v1/customer/change-password
  #   method: POST
  #   headers:
  #     - "Content-Type: application/json"
  #     - "Authorization: Bearer YOUR_ACCESS_TOKEN"  # Replace YOUR_ACCESS_TOKEN with a valid token or use a secret
  #   body: '{"current_password": "your_current_password_here", "password": "your_new_password_here", "password_confirmation": "your_new_password_here"}'
  #   expectedStatusCodes:
  #     - 200
  #     - 422
  #   check: "http"
  # - name: Customer Files Add API
  #   url: https://app.connecthear.org/api/v1/customer/files-add
  #   method: POST
  #   body: '{"avatar": "<base64_encoded_image>", "cnic": "<base64_encoded_image>"}'
  #   expectedStatusCodes:
  #     - 200
  #     - 422
  #   check: "https"
  #   headers:
  #     - "Content-Type: application/json"
  #     - "Authorization: Bearer <your_access_token>"
  # - name: Customer Add Reviews API
  #   url: https://app.connecthear.org/api/v1/customer/add-reviews
  #   method: POST
  #   body: '{"monitoring_id": "example_monitoring_id", "rating": 4, "reviews": "This is a test review."}'
  #   expectedStatusCodes:
  #     - 200
  #     - 422
  #   check: "https"
  #   headers:
  #     - "Content-Type: application/json"
  #     - "Authorization: Bearer <your_access_token>"
  # - name: Customer Complaint API
  #   url: https://app.connecthear.org/api/v1/customer/create-complaint
  #   method: POST
  #   body: '{"contact_number": "1234567890", "complaint": "This is a test complaint."}'
  #   expectedStatusCodes:
  #     - 200
  #     - 422
  #   check: "https"
  #   headers:
  #     - "Content-Type: application/json"
  #     - "Authorization: Bearer your_access_token"
  # - name: Customer Create Video Session API
  #   url: https://app.connecthear.org/api/v1/customer/create-video-session
  #   method: POST
  #   body: '{"latitude": 25.276987, "longitude": 55.296249}'
  #   expectedStatusCodes:
  #     - 200
  #     - 402
  #     - 422
  #   check: "https"
  #   headers:
  #     - "Content-Type: application/json"
  #     - "Authorization: Bearer your_access_token"
  # - name: Customer Create Call API
  #   url: https://app.connecthear.org/api/v1/customer/create-call
  #   method: POST
  #   body: '{"monitoring_id": "example-monitoring-id"}'
  #   expectedStatusCodes:
  #     - 200
  #     - 422
  #   check: "https"
  #   headers:
  #     - "Content-Type: application/json"
  #     - "Authorization: Bearer your_access_token"
  # - name: ConnectHear Get Reviews API
  #   url: https://app.connecthear.org/api/v1/customer/get-reviews
  #   method: GET
  #   expectedStatusCodes:
  #     - 200
  #   check: "https"
  #   headers:
  #     - "Authorization: Bearer {your_token_here}"  # Replace with appropriate authorization if needed
  # - name: Customer Plans API
  #   url: https://app.connecthear.org/api/v1/customer/get-plans
  #   method: GET
  #   expectedStatusCodes:
  #     - 200
  #   check: "https"
  #   headers:
  #     - "Authorization: Bearer your_access_token"
  # - name: Customer Update Profile API
  #   url: https://app.connecthear.org/api/v1/customer/update-profile
  #   method: POST
  #   body: '{"name": "Test User", "date_of_birth": "1990-01-01", "gender": "Male", "mobile_number": "1234567890", "avatar": "base64_encoded_image_data"}'
  #   expectedStatusCodes:
  #     - 200
  #     - 422
  #   check: "https"
  #   headers:
  #     - "Content-Type: application/json"
  #     - "Authorization: Bearer your_access_token"
  # - name: Customer Subscription API
  #   url: https://app.connecthear.org/api/v1/customer/make-subscription
  #   method: POST
  #   body: '{"plan_id": "123456"}'
  #   expectedStatusCodes:
  #     - 200
  #     - 400
  #   check: "https"
  #   headers:
  #     - "Content-Type: application/json"
  #     - "Authorization: Bearer your_access_token"
  # - name: Customer Update Monitoring Session Status API
  #   url: https://app.connecthear.org/api/v1/customer/update-monitoring-session-status
  #   method: POST
  #   body: '{"monitoring_id": "abc123", "status": 2, "call_duration": "00:30:00"}'
  #   expectedStatusCodes:
  #     - 200
  #     - 422
  #   check: "https"
  #   headers:
  #     - "Content-Type: application/json"
  #     - "Authorization: Bearer your_access_token"
  # - name: Customer Get Call Logs API
  #   url: https://app.connecthear.org/api/v1/customer/get-call-logs
  #   method: GET
  #   expectedStatusCodes:
  #     - 200
  #   check: "https"
  #   headers:
  #     - "Authorization: Bearer <your_token>"
  - name: Interpreter Sign-Up API
    url: https://app.connecthear.org/api/v1/interpreter/sign-up
    method: POST
    body: '{"name": "John Doe", "email": "john.doe@example.com", "password": "your_password", "mobile_number": "1234567890", "gender": "male", "date_of_birth": "1990-01-01", "occupation": "Interpreter", "address": "123 Main St", "latitude": "34.0522", "longitude": "-118.2437", "avatar": "base64_encoded_image", "cnic": "base64_encoded_cnic"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "https"
    headers:
      - "Content-Type: application/json"
  - name: Interpreter Verify SMS Code API
    url: https://app.connecthear.org/api/v1/interpreter/verify-sms-code
    method: POST
    body: '{"email": "john.doe@example.com", "password": "your_password", "mobile_number": "1234567890", "otp": "1234"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "https"
    headers:
      - "Content-Type: application/json"
  - name: Interpreter Login API
    url: https://app.connecthear.org/api/v1/interpreter/login
    method: POST
    body: '{"email": "john.doe@example.com", "password": "your_password"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "https"
    headers:
      - "Content-Type: application/json"
  - name: Interpreter Google Login API
    url: https://app.connecthear.org/api/v1/interpreter/google-login
    method: POST
    body: '{"name": "John Doe", "email": "john.doe@example.com", "google_id": "your_google_id"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "https"
    headers:
      - "Content-Type: application/json"
  - name: Interpreter Forgot Password API
    url: https://app.connecthear.org/api/v1/interpreter/forgot-password
    method: POST
    body: '{"email": "john.doe@example.com"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "https"
    headers:
      - "Content-Type: application/json"
  - name: Interpreter Verify Code API
    url: https://app.connecthear.org/api/v1/interpreter/verify-code
    method: POST
    body: '{"email": "john.doe@example.com", "verification_code": "1234"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "https"
    headers:
      - "Content-Type: application/json"
  - name: Interpreter Reset Password API
    url: https://app.connecthear.org/api/v1/interpreter/reset-password
    method: POST
    body: '{"email": "john.doe@example.com", "password": "new_password", "password_confirmation": "new_password"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "https"
    headers:
      - "Content-Type: application/json"
  # - name: Interpreter Files Add API
  #   url: https://app.connecthear.org/api/v1/interpreter/files-add
  #   method: POST
  #   expectedStatusCodes:
  #     - 200
  #     - 422
  #   check: "https"
  #   body: '{"avatar": "base64_encoded_avatar", "cnic": "base64_encoded_cnic"}'
  #   headers:
  #     - "Content-Type: application/json"
  #     - "Authorization: Bearer your_access_token"
  # - name: Interpreter Update Device Token API
  #   url: https://app.connecthear.org/api/v1/interpreter/update-device-token
  #   method: POST
  #   expectedStatusCodes:
  #     - 200
  #     - 422
  #   check: "https"
  #   body: '{"device_token": "your_device_token", "device_type": "your_device_type"}'
  #   headers:
  #     - "Content-Type: application/json"
  #     - "Authorization: Bearer your_access_token"
  # - name: Interpreter Logout API
  #   url: https://app.connecthear.org/api/v1/interpreter/logout
  #   method: POST
  #   expectedStatusCodes:
  #   - 200
  #   - 422
  #   check: "https"
  #   body: {}
  #   headers:
  #     - "Authorization: Bearer your_access_token"
  # - name: Interpreter Get Profile API
  #   url: https://app.connecthear.org/api/v1/interpreter/get-profile
  #   method: GET
  #   expectedStatusCodes:
  #     - 200
  #     - 401
  #   check: "https"
  #   body: {}
  #   headers:
  #     - "Authorization: Bearer your_access_token"
  # - name: Interpreter Change Password API
  #   url: https://app.connecthear.org/api/v1/interpreter/change-password
  #   method: POST
  #   body: '{"current_password": "current_password", "password": "new_password", "password_confirmation": "new_password"}'
  #   expectedStatusCodes:
  #     - 200
  #     - 422
  #   check: "https"
  #   headers:
  #     - "Authorization: Bearer your_access_token"
  #     - "Content-Type: application/json"

  # - name: Interpreter Create Complaint API
  #   url: https://app.connecthear.org/api/v1/interpreter/create-complaint
  #   method: POST
  #   body: '{"contact_number": "1234567890", "complaint": "Complaint description here"}'
  #   expectedStatusCodes:
  #     - 200
  #     - 422
  #   check: "https"
  #   headers:
  #     - "Content-Type: application/json"
  #     - "Authorization: Bearer your_access_token"
  # - name: Interpreter Update Archive ID API
  #   url: https://app.connecthear.org/api/v1/interpreter/update-archive-id
  #   method: POST
  #   body: '{"monitoring_id": "your_monitoring_id"}'
  #   expectedStatusCodes:
  #     - 200
  #     - 422
  #   check: "https"
  #   headers:
  #     - "Authorization: Bearer your_access_token"
  #     - "Content-Type: application/json"
  # - name: Interpreter Get Reviews API
  #   url: https://app.connecthear.org/api/v1/interpreter/get-reviews
  #   method: GET
  #   expectedStatusCodes:
  #     - 200
  #     - 422
  #   check: "https"
  #   headers:
  #     - "Authorization: Bearer your_access_token"
  #     - "Content-Type: application/json"
  # - name: Interpreter Update Profile API
  #   url: https://app.connecthear.org/api/v1/interpreter/update-profile
  #   method: POST
  #   body: '{"name": "John Doe", "date_of_birth": "1990-01-01", "gender": "male", "occupation": "Interpreter", "address": "123 Street, City", "avatar": "avatar_base64_string"}'
  #   expectedStatusCodes:
  #     - 200
  #     - 422
  #   check: "https"
  #   headers:
  #     - "Authorization: Bearer your_access_token"
  #     - "Content-Type: application/json"

  # - name: Interpreter Update Monitoring Session Status API
  #   url: https://app.connecthear.org/api/v1/interpreter/update-monitoring-session-status
  #   method: POST
  #   body: '{"monitoring_id": "example_monitoring_id", "status": 1, "call_duration": "00:30:00"}'
  #   expectedStatusCodes:
  #     - 200
  #     - 422
  #   check: "https"
  #   headers:
  #     - "Authorization: Bearer your_access_token"
  #     - "Content-Type: application/json"

  # - name: Interpreter Add Reviews API
  #   url: https://app.connecthear.org/api/v1/interpreter/add-reviews
  #   method: POST
  #   body: '{"monitoring_id": "example_monitoring_id", "rating": 4, "reviews": "Great session!"}'
  #   expectedStatusCodes:
  #     - 200
  #     - 422
  #   check: "https"
  #   headers:
  #     - "Authorization: Bearer your_access_token"
  #     - "Content-Type: application/json"

  # - name: Interpreter Update Latitude and Longitude API
  #   url: https://app.connecthear.org/api/v1/interpreter/update-latitude-longitude
  #   method: POST
  #   body: '{"latitude": 24.8607, "longitude": 67.0011}'
  #   expectedStatusCodes:
  #     - 200
  #     - 422
  #   check: "https"
  #   headers:
  #     - "Authorization: Bearer your_access_token"
  #     - "Content-Type: application/json"
  # - name: Interpreter Get Call Logs API
  #   url: https://app.connecthear.org/api/v1/interpreter/get-call-logs
  #   method: GET
  #   expectedStatusCodes:
  #     - 200
  #     - 422
  #   check: "https"
  #   headers:
  #     - "Authorization: Bearer your_access_token"
  #     - "Content-Type: application/json"
  # - name:  Interpreter Manage Online Status API
  #   url: https://app.connecthear.org/api/v1/interpreter/online-status
  #   method: POST
  #   expectedStatusCodes:
  #     - 200
  #     - 422
  #   check: "https"
  #   headers:
  #     - "Authorization: Bearer your_access_token"
  #     - "Content-Type: application/json"
  # - name: Interpreter Update Time API
  #   url: https://app.connecthear.org/api/v1/interpreter/update-time
  #   method: POST
  #   expectedStatusCodes:
  #   - 200
  #   - 422
  #   check: "https"
  #   headers:
  #     - "Authorization: Bearer your_access_token"
  #     - "Content-Type: application/json"

status-website:
  baseUrl: /v1-app-uptime
  logoUrl: https://avatars.githubusercontent.com/u/94858144?s=400&u=21671f502bedc2181ba2a90086fcf842d6231d1c&v=4
  name: ConnectHear v1 App Uptime
  introTitle: "This is ConnectHear's uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/ConnectHear/v1-app-runtime). No server required — just GitHub Actions, Issues, and Pages. 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/connecthear/v1-app-uptime

