owner: connecthear  # Your GitHub username
repo: v1-app-uptime # The name of this repository

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Trigger the `main.yml` workflow
    - name: Trigger main.yml Workflow
      id: trigger_main
      run: |
        curl -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches \
        -d '{"ref":"main"}'
    
    # Step 2: Wait for the completion of `main.yml` (Polling)
    - name: Wait for main.yml completion
      id: wait_for_main
      run: |
        workflow_id=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/repos/${{ github.repository }}/actions/runs \
        | jq -r '.workflow_runs[] | select(.name == "Custom Uptime Workflow" and .status == "in_progress") | .id')

        echo "Waiting for workflow $workflow_id to complete..."

        while [[ $(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/actions/runs/$workflow_id | jq -r '.status') == "in_progress" ]]; do
          echo "Workflow is still in progress... waiting 30 seconds"
          sleep 30
        done
        
        status=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/actions/runs/$workflow_id | jq -r '.conclusion')

        if [[ "$status" != "success" ]]; then
          echo "Custom Uptime Workflow Workflow failed"
          exit 1
        fi
        echo "Custom Uptime Workflow completed successfully"

sites:
  - name: Customer Sign-Up API
    url: https://app.connecthear.org/api/v1/customer/sign-up
    method: POST
    body: '{"name": "Test User", "email": "uptime@connecthear.org", "password": "connecthearapplicationdevelopment","date_of_birth": "1990-01-01","mobile_number": "1234567890","gender": "Male","latitude": "25.276987","longitude": "55.296249","code": ""}'
    expectedStatusCodes:
      - 200
      - 201
      - 422
    check: "http"
    headers:
      - "Content-Type: application/json"
  - name: Customer Login API # Monitoring the login API
    url: https://app.connecthear.org/api/v1/customer/login
    method: POST
    body: '{"email": "uptime@connecthear.org", "password": "connecthearapplicationdevelopment"}'
    expectedStatusCodes:
      - 200
      - 401
      - 422
    check: "http"
    headers:
      - "Content-Type: application/json"
      
  - name: Customer Google Login API # Monitoring the Google Login API
    url: https://app.connecthear.org/api/v1/customer/google-login
    method: POST
    body: '{"name": "Upptime", "email": "uptime@connecthear.org", "google_id": "{{TOKEN}}"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "http"
    headers:
      - "Content-Type: application/json"
  - name: Customer Forgot Password API # Monitoring the Forgot Password API
    url: https://app.connecthear.org/api/v1/customer/forgot-password
    method: POST
    body: '{"email": "uptime@connecthear.org"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "http"
    headers:
      - "Content-Type: application/json"
  - name: Customer Code Verification API # Monitoring the Verify Code API
    url: https://app.connecthear.org/api/v1/customer/verify-code
    method: POST
    body: '{"email": "uptime@connecthear.org", "verification_code": "1234", "password": "connecthearapplicationdevelopment", "password_confirmation": "connecthearapplicationdevelopment1"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "http"
    headers:
      - "Content-Type: application/json"
  - name: Customer SMS Code Verification API # Monitoring the Verify SMS Code API
    url: https://app.connecthear.org/api/v1/customer/verify-sms-code
    method: POST
    body: '{"email": "uptime@connecthear.org", "password": "connecthearapplicationdevelopment", "mobile_number": "1234567890", "verification_code": "1234"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "http"
    headers:
      - "Content-Type: application/json"
  - name: Customer Password Reset API # Monitoring the Reset Password API
    url: https://app.connecthear.org/api/v1/customer/reset-password
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{"email": "uptime@connecthear.org", "password": "connecthearapplicationdevelopment", "password_confirmation": "connecthearapplicationdevelopment"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "http"
  - name: Customer Resend OTP API # Monitoring the Resend OTP API
    url: https://app.connecthear.org/api/v1/customer/resend-otp
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{"email": "uptime@connecthear.org"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "http"
  - name: Customer Get Profile API # Monitoring the Get Profile API
    url: https://app.connecthear.org/api/v1/customer/get-profile
    method: GET
    headers:
      - "Content-Type: application/json;charset=UTF-8"
      - "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjliOWI1ZmMyZjhlZjViODgyMTE0MDk0MGIxODZjMzk4MDI3NjY4YTZlMmE2MDQ0OTYwZTJmNzNiMGFmNmZlMzg4NzhkY2I2YTc4MzA2NWE1In0.eyJhdWQiOiIxIiwianRpIjoiOWI5YjVmYzJmOGVmNWI4ODIxMTQwOTQwYjE4NmMzOTgwMjc2NjhhNmUyYTYwNDQ5NjBlMmY3M2IwYWY2ZmUzODg3OGRjYjZhNzgzMDY1YTUiLCJpYXQiOjE3MjkwMDEyODMsIm5iZiI6MTcyOTAwMTI4MywiZXhwIjoxNzYwNTM3MjgzLCJzdWIiOiIxNTY4NCIsInNjb3BlcyI6W119.ddnBLb0uR8mQ86WQ--OyloOk-oig2yn2J_6HM0biDMcZy4a5Mjji6iWPwf_vt72AJUfUbsE2ie_ez8k5kG44BLeI6mVfIVNTnSSHBFWGjPctCeztcEsTsHO5Eewh2Pt4ytR8hl1VzxV-8d1ffNHLqKVUwj548_gKs5SYKmU3nOjS3SIZouCQE5vHC0BdF3Yn7pUnZkqhr8wxiYggm8TW7jWKO3-xrPAnJGFpvU8wr03kQYkFdcRnqgaaP38sKIBeStUUD7HGZ7FuhSBVyjMWZEdS9Ixnz6d5_ya3iap-gV5AQegxUuDoMCEVGdu28PCN01I68d2dkq8c5TAWFdOkkFDhe0rJ_mUQVQlO_taBZKGuW6jRVPrDfGbSzyWB21rejeMc9YBsXbgM0xYl4WQOPAAHA7RFJDZ82C1Q1q29wtnQUX6q5SHdc9xTY9r4aHifXfQbHhr9G2cInQa3ryVvK-m9UlkugA0gk6aLtHrpbYEe9H8lAwmwOIZo8T3cscQUo5Ictvr-NLcsnXLf91Ti0AfJbmjjadEl9OiB23wFweh0jlwvzPgP80mKyXWjDH9aqjSueU0mCZNoIx9SH8AMtUwaUF1viYL8Y6BsbBXNWgdi3g2dfyLNM-yW8ibvIodFUJE9SUb1H4mCKWgEEeCXG7FtO9ahmyy3iOX7xEv1skg"  # Token will be dynamically replaced
    expectedStatusCodes:
      - 200
      - 403  # Account disabled by user or company
    check: "http"
  - name: Customer Change Password API # Monitoring the Change Password API
    url: https://app.connecthear.org/api/v1/customer/change-password
    method: POST
    headers:
      - "Content-Type: application/json"
      - "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjliOWI1ZmMyZjhlZjViODgyMTE0MDk0MGIxODZjMzk4MDI3NjY4YTZlMmE2MDQ0OTYwZTJmNzNiMGFmNmZlMzg4NzhkY2I2YTc4MzA2NWE1In0.eyJhdWQiOiIxIiwianRpIjoiOWI5YjVmYzJmOGVmNWI4ODIxMTQwOTQwYjE4NmMzOTgwMjc2NjhhNmUyYTYwNDQ5NjBlMmY3M2IwYWY2ZmUzODg3OGRjYjZhNzgzMDY1YTUiLCJpYXQiOjE3MjkwMDEyODMsIm5iZiI6MTcyOTAwMTI4MywiZXhwIjoxNzYwNTM3MjgzLCJzdWIiOiIxNTY4NCIsInNjb3BlcyI6W119.ddnBLb0uR8mQ86WQ--OyloOk-oig2yn2J_6HM0biDMcZy4a5Mjji6iWPwf_vt72AJUfUbsE2ie_ez8k5kG44BLeI6mVfIVNTnSSHBFWGjPctCeztcEsTsHO5Eewh2Pt4ytR8hl1VzxV-8d1ffNHLqKVUwj548_gKs5SYKmU3nOjS3SIZouCQE5vHC0BdF3Yn7pUnZkqhr8wxiYggm8TW7jWKO3-xrPAnJGFpvU8wr03kQYkFdcRnqgaaP38sKIBeStUUD7HGZ7FuhSBVyjMWZEdS9Ixnz6d5_ya3iap-gV5AQegxUuDoMCEVGdu28PCN01I68d2dkq8c5TAWFdOkkFDhe0rJ_mUQVQlO_taBZKGuW6jRVPrDfGbSzyWB21rejeMc9YBsXbgM0xYl4WQOPAAHA7RFJDZ82C1Q1q29wtnQUX6q5SHdc9xTY9r4aHifXfQbHhr9G2cInQa3ryVvK-m9UlkugA0gk6aLtHrpbYEe9H8lAwmwOIZo8T3cscQUo5Ictvr-NLcsnXLf91Ti0AfJbmjjadEl9OiB23wFweh0jlwvzPgP80mKyXWjDH9aqjSueU0mCZNoIx9SH8AMtUwaUF1viYL8Y6BsbBXNWgdi3g2dfyLNM-yW8ibvIodFUJE9SUb1H4mCKWgEEeCXG7FtO9ahmyy3iOX7xEv1skg"  # Token will be dynamically replaced
    body: '{"current_password": "your_current_password_here", "password": "your_new_password_here", "password_confirmation": "your_new_password_here"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "http"
  - name: Customer Update Device Token API # Monitoring the Update Device Token API
    url: https://app.connecthear.org/api/v1/customer/update-device-token
    method: POST
    headers:
      - "Content-Type: application/json"
      - "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjliOWI1ZmMyZjhlZjViODgyMTE0MDk0MGIxODZjMzk4MDI3NjY4YTZlMmE2MDQ0OTYwZTJmNzNiMGFmNmZlMzg4NzhkY2I2YTc4MzA2NWE1In0.eyJhdWQiOiIxIiwianRpIjoiOWI5YjVmYzJmOGVmNWI4ODIxMTQwOTQwYjE4NmMzOTgwMjc2NjhhNmUyYTYwNDQ5NjBlMmY3M2IwYWY2ZmUzODg3OGRjYjZhNzgzMDY1YTUiLCJpYXQiOjE3MjkwMDEyODMsIm5iZiI6MTcyOTAwMTI4MywiZXhwIjoxNzYwNTM3MjgzLCJzdWIiOiIxNTY4NCIsInNjb3BlcyI6W119.ddnBLb0uR8mQ86WQ--OyloOk-oig2yn2J_6HM0biDMcZy4a5Mjji6iWPwf_vt72AJUfUbsE2ie_ez8k5kG44BLeI6mVfIVNTnSSHBFWGjPctCeztcEsTsHO5Eewh2Pt4ytR8hl1VzxV-8d1ffNHLqKVUwj548_gKs5SYKmU3nOjS3SIZouCQE5vHC0BdF3Yn7pUnZkqhr8wxiYggm8TW7jWKO3-xrPAnJGFpvU8wr03kQYkFdcRnqgaaP38sKIBeStUUD7HGZ7FuhSBVyjMWZEdS9Ixnz6d5_ya3iap-gV5AQegxUuDoMCEVGdu28PCN01I68d2dkq8c5TAWFdOkkFDhe0rJ_mUQVQlO_taBZKGuW6jRVPrDfGbSzyWB21rejeMc9YBsXbgM0xYl4WQOPAAHA7RFJDZ82C1Q1q29wtnQUX6q5SHdc9xTY9r4aHifXfQbHhr9G2cInQa3ryVvK-m9UlkugA0gk6aLtHrpbYEe9H8lAwmwOIZo8T3cscQUo5Ictvr-NLcsnXLf91Ti0AfJbmjjadEl9OiB23wFweh0jlwvzPgP80mKyXWjDH9aqjSueU0mCZNoIx9SH8AMtUwaUF1viYL8Y6BsbBXNWgdi3g2dfyLNM-yW8ibvIodFUJE9SUb1H4mCKWgEEeCXG7FtO9ahmyy3iOX7xEv1skg"  # Token will be dynamically replaced
    body: '{"device_token": "your_device_token_here", "device_type": "your_device_type_here"}'
    expectedStatusCodes:
      - 200
      - 422
    check: "http"

# Additional APIs can be added following the same structure

status-website:
  baseUrl: /v1-app-uptime
  logoUrl: https://avatars.githubusercontent.com/u/94858144?s=400&u=21671f502bedc2181ba2a90086fcf842d6231d1c&v=4
  name: ConnectHear v1 App Uptime
  introTitle: "This is ConnectHear's uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/ConnectHear/v1-app-uptime). No server required — just GitHub Actions, Issues, and Pages. 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/connecthear/v1-app-uptime
