name: Setup CI

on:
  push:
    paths:
      - ".upptimerc.yml"
  repository_dispatch:
    types: [setup]
  workflow_dispatch:

jobs:
  release:
    name: Setup Upptime
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT || github.token }}

      # Call the Main.yml workflow first
      - name: Trigger Main CI workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: main.yml
          token: ${{ secrets.GH_PAT || github.token }}

      # Ensure the dynamic token is generated after running Main CI
      - name: Generate Dynamic Token
        id: token_step
        run: |
          TOKEN=$(curl -X POST https://app.connecthear.org/api/v1/customer/login \
          -H "Content-Type: application/json" \
          -d '{"email": "uptime@connecthear.org", "password": "connecthearapplicationdevelopment"}' | \
          jq -r '.response.detail.token_detail.access_token')
          echo "TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Update template
        uses: upptime/uptime-monitor@v1.38.0
        with:
          command: "update-template"
        env:
          GH_PAT: ${{ secrets.GH_PAT || github.token }}
          TOKEN: ${{ steps.token_step.outputs.TOKEN }}

      - name: Update response time
        uses: upptime/uptime-monitor@v1.38.0
        with:
          command: "response-time"
        env:
          GH_PAT: ${{ secrets.GH_PAT || github.token }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}

      - name: Update summary in README
        uses: upptime/uptime-monitor@v1.38.0
        with:
          command: "readme"
        env:
          GH_PAT: ${{ secrets.GH_PAT || github.token }}

      - name: Generate graphs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Graphs CI
          token: ${{ secrets.GH_PAT || github.token }}

      - name: Generate site
        uses: upptime/uptime-monitor@v1.38.0
        with:
          command: "site"
        env:
          GH_PAT: ${{ secrets.GH_PAT || github.token }}

      - uses: peaceiris/actions-gh-pages@v4
        name: GitHub Pages Deploy
        with:
          github_token: ${{ secrets.GH_PAT || github.token }}
          publish_dir: "site/status-page/__sapper__/export/"
          force_orphan: "false"
          user_name: "Upptime Bot"
          user_email: "73812536+upptime-bot@users.noreply.github.com"
